# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-15 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteractionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('chilling', 'Chilling'), ('line_item_description_awaited', 'Line item description awaited'), ('line_item_amount_awaited', 'Line item amount awaited')], default='chilling', max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee')),
            ],
        ),
    ]
