# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-15 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteractionstate',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui_state', to='accounts.Employee'),
        ),
    ]
