# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-14 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Not Paid')], default='unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_status',
            field=models.CharField(choices=[('sent', 'Sent'), ('not_sent', 'Not Sent')], default='not_sent', max_length=10),
        ),
    ]
