# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-15 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('actions', '0003_auto_20170614_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='edited_details_awaited_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee'),
        ),
    ]
