# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-16 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_lineitem_edited_details_awaited_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cancel_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='confirmation_status',
            field=models.BooleanField(default=False),
        ),
    ]
