# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-19 10:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_invoice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 6, 19, 10, 27, 1, 65438, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
