# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-20 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_lineitem_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
